# Generated by Django 3.1.4 on 2021-06-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('imageUrl', models.CharField(max_length=50)),
                ('sketch', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('imageUrl', models.CharField(default='img/Exteriores.jpg', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue', to='darwinApp.venue')),
            ],
            options={
                'verbose_name_plural': 'Productions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
