# Generated by Django 3.1.4 on 2021-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darwinApp', '0003_auto_20210609_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
