# Generated by Django 3.1.4 on 2021-06-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinApp', '0004_auto_20210609_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(default='img/Exteriores.jpg', max_length=60)),
                ('production_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='darwinApp.production')),
            ],
        ),
    ]
