# Generated by Django 3.1.4 on 2021-06-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darwinApp', '0005_productionpics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionpics',
            old_name='production_id',
            new_name='production',
        ),
    ]
