# Generated by Django 3.1.4 on 2021-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darwinApp', '0006_auto_20210609_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionpics',
            options={'verbose_name_plural': 'Production Pics'},
        ),
        migrations.AddField(
            model_name='production',
            name='video',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
