# Generated by Django 3.1.4 on 2021-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darwinApp', '0007_auto_20210609_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='video',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
