# Generated by Django 3.1.4 on 2021-06-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinApp', '0008_auto_20210609_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(default='img/Exteriores.jpg', max_length=60)),
                ('venueName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venueName', to='darwinApp.venue')),
            ],
            options={
                'verbose_name_plural': 'Venue Pics',
            },
        ),
    ]
