# Generated by Django 3.1.4 on 2021-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darwinApp', '0009_venuepics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='artist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
